#!/bin/bash

clear

echo "=================================================="
echo "        SHERIF ROLE DEMO"
echo " Ubuntu Infrastructure + AI + Containment"
echo "=================================================="
echo ""

echo "[1] Project Source of Truth"
echo "Ubuntu Server is the official source of truth."
echo "Official outputs are stored in:"
echo "~/soc_project/outputs"
echo ""

cd ~/soc_project || exit

echo "--------------------------------------------------"
echo "[2] Official Outputs Folder"
echo "--------------------------------------------------"
ls -lh outputs | grep -E "ai_analysis|alerts|correlation|containment|firewall|system_health|live_attack|detection"
echo ""

echo "--------------------------------------------------"
echo "[3] Alert Generated by Detection"
echo "--------------------------------------------------"
cat outputs/alerts.json | jq .
echo ""

echo "--------------------------------------------------"
echo "[4] Correlation Result"
echo "--------------------------------------------------"
cat outputs/correlation.json | jq .
echo ""

echo "--------------------------------------------------"
echo "[5] AI Analysis Result"
echo "--------------------------------------------------"
cat outputs/ai_analysis.json | jq .
echo ""

echo "--------------------------------------------------"
echo "[6] Containment Status"
echo "--------------------------------------------------"
cat outputs/containment_status.json | jq .
echo ""

echo "--------------------------------------------------"
echo "[7] Firewall Actions Evidence"
echo "NOTE: This file has formatting issue for jq, so displaying raw content."
echo "--------------------------------------------------"
cat outputs/firewall_actions.json
echo ""

echo "--------------------------------------------------"
echo "[8] System Health"
echo "--------------------------------------------------"
cat outputs/system_health.json | jq .
echo ""

echo "--------------------------------------------------"
echo "[9] UFW Firewall Status"
echo "--------------------------------------------------"
sudo ufw status numbered
echo ""

echo "--------------------------------------------------"
echo "[10] Final Attack Snapshot - AI + Containment"
echo "--------------------------------------------------"
echo "AI Analysis Snapshot:"
cat final_attack_snapshot/ai_analysis.json | jq .
echo ""

echo "Containment Snapshot:"
cat final_attack_snapshot/containment_status.json | jq .
echo ""

echo "=================================================="
echo " SHERIF DEMO COMPLETE"
echo "=================================================="
